/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.server;


import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.net.UnknownHostException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel
 */
public class ClientForm extends javax.swing.JFrame {

    Socket server = null;
    DataInputStream dis = null;
    DataOutputStream dos = null;
    
    // para coneccion 
    private String buscar="";
    private String user = "root";
    private String password = "";
    private String url = "jdbc:mysql://localhost:3306/chat";
    private ResultSet rs,rs1;
    private Object[] fila = new Object[3];
    //-----------------
    
    /**
     * Creates new form ClientRorm
     */
    public ClientForm() {
        super("CLIENT");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton_conectar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_RecMsg = new javax.swing.JTextArea();
        txt_msg = new javax.swing.JTextField();
        boton_buscar = new javax.swing.JButton();
        boton_enviar = new javax.swing.JButton();
        label_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_conectar.setBackground(new java.awt.Color(204, 204, 204));
        boton_conectar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        boton_conectar.setText("Connect");
        boton_conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_conectarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_conectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 22, 110, 50));

        txt_RecMsg.setBackground(new java.awt.Color(204, 204, 204));
        txt_RecMsg.setColumns(20);
        txt_RecMsg.setRows(5);
        jScrollPane1.setViewportView(txt_RecMsg);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 370, 110));

        txt_msg.setBackground(new java.awt.Color(204, 204, 204));
        txt_msg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_msgActionPerformed(evt);
            }
        });
        getContentPane().add(txt_msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 370, 40));

        boton_buscar.setBackground(new java.awt.Color(204, 204, 204));
        boton_buscar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        boton_buscar.setText("Search");
        boton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 160, 40));

        boton_enviar.setBackground(new java.awt.Color(204, 204, 204));
        boton_enviar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        boton_enviar.setText("Send");
        boton_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_enviarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 150, 50));

        label_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(label_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_conectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_conectarActionPerformed
        try {
            // TODO add your handling code here:
            server = new Socket("127.0.0.1",6969);
            JOptionPane.showMessageDialog(null,"Conectado al Servidor");
            dis = new DataInputStream(server.getInputStream());
            dos = new DataOutputStream(server.getOutputStream());
            
            ReceiveMessage clientThread = new ReceiveMessage(dis, txt_RecMsg);
            clientThread.setDaemon(true);
            clientThread.setName("Server :");
            clientThread.start();
            
        } catch (UnknownHostException ex) {
            JOptionPane.showMessageDialog(null,"Conexion Fallida");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null,"Conexion Fallida");
        }
        
    }//GEN-LAST:event_boton_conectarActionPerformed

    private void txt_msgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_msgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_msgActionPerformed

    private void boton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscarActionPerformed
        
        buscar = txt_msg.getText().toUpperCase();
      
        try {

        for(int i=0;i<=2;i++)
        {
            fila[i]="0";
        }

        Connection conexion = DriverManager.getConnection(url, user, password);
        Statement s = conexion.createStatement();
            
        rs = s.executeQuery ("select * from personas where nombre like '"+buscar+"'");
        
 
        while(rs.next())
        {
            fila[0] = rs.getString(1);
            fila[1] = rs.getString(2);
            fila[2] = rs.getString(3);
        }
            
        if(fila[0] == "0")
        {
            rs = s.executeQuery ("select * from personas where apellido like '"+buscar+"'");
            
            while(rs.next())
            {
                fila[0] = rs.getString(1);
                fila[1] = rs.getString(2);
                fila[2] = rs.getString(3);
            }
        }
                  
        if(fila[0] == "0")
        {
            JOptionPane.showMessageDialog(null,"Persona no encontrada"); 
        }
        else
        {
            txt_msg.setText(fila[1]+" "+fila[2] );
        }
                     
        } catch (SQLException ex) {
            Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
       
        
    }//GEN-LAST:event_boton_buscarActionPerformed

    private void boton_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_enviarActionPerformed
        // TODO add your handling code here:
        try {
            dos.writeUTF(txt_msg.getText());
        } catch (IOException ex) {
            Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        txt_msg.setText("");

    }//GEN-LAST:event_boton_enviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_buscar;
    private javax.swing.JButton boton_conectar;
    private javax.swing.JButton boton_enviar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_fondo;
    private javax.swing.JTextArea txt_RecMsg;
    private javax.swing.JTextField txt_msg;
    // End of variables declaration//GEN-END:variables
}
